version: '3'

services:
  db:
    image: mariadb:11.7.2
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=c32LabCotifyDEMO
      - MYSQL_DATABASE=cotify
      - MYSQL_USER=cotify
      - MYSQL_PASSWORD=c32LabCotifyDEMO
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - TZ=Asia/Shanghai
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-read-only-compressed=OFF"
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - db
  cotify:
    image: cotify:latest
    restart: always
    ports:
      - 80:80
    environment:
      - DB_NAME=cotify
      - DB_USER=cotify
      - DB_PASSWORD=c32LabCotifyDEMO
      - DB_PORT=3306
      - DB_HOST=db
      - SERVER_PORT=80
    depends_on:
      - db

 